### PR TITLE
some updates

### PR DESCRIPTION
**Pull request by mkz212**
I am still testing the beta. I added a special page for the new feature - Advanced Control. Also small changes For better informing users.

### CODE REVIEW

**Comment by mkz212** [comment]
@ilcato can you merge it and releas as beta 2 ? I'm going to the second location in a moment to test the second Home Center (HC 2 Lite).

**Comment by ilcato** [comment]
@mkz212 published homebridge-fibaro-home-center@1.5.0-beta.2

**Comment by ilcato** [comment]
@mkz212 may I add you as an admin to the repo?

**Comment by mkz212** [comment]
@ilcato Thank you for this proposal but I do not know on github enough to administer.

**Comment by ilcato** [comment]
@mkz212, try to give meaningful names to PR and commits in general

**Pull request merged**
