### PR TITLE
DeviceGrouping

### PR DESCRIPTION
**Pull request by lboue**
Hello,

I enabling this _deviceGrouping_debug_ to try to fix issues #111 
Do you have a proposal to fix this issue?

Regards

### CODE REVIEW

**Comment by ilcato** [comment]
@lboue can you test the last commit: https://github.com/ilcato/homebridge-fibaro-home-center/commit/a786c66e60d18f8cb3055471e9aac0956112135c

**Comment by lboue** [comment]
> @lboue is the "deviceGrouping" interface present in the flood sensor device that you mention in #111 ?

Yes as following:
- Device 178: parent Device / batteryLevel: "79"
- - Device 179: floodSensor / batteryLevel: "79"
- - Device 181: temperatureSensor / batteryLevel: "79"

**Comment by ilcato** [comment]
@lboue can you test version 1.2.14 ?

**Comment by lboue** [comment]
I am still having the callback issue with homebridge-fibaro-home-center v1.2.14:

```
[9/14/2022, 10:00:05 PM] ---
[9/14/2022, 10:00:05 PM] Loaded plugin: homebridge-fibaro-home-center@1.2.14
[9/14/2022, 10:00:05 PM] Registering platform 'homebridge-fibaro-home-center.FibaroHC'
[9/14/2022, 10:00:05 PM] ---

9/14/2022, 10:00:58 PM] [Fibaro-HC2] Getting value from device:  179  parameter: Leak Detected
[9/14/2022, 10:00:58 PM] [Fibaro-HC2] Getting value from device:  179  parameter: Status Low Battery
[9/14/2022, 10:00:58 PM] [Fibaro-HC2] Getting value from device:  179  parameter: Status Low Battery
[9/14/2022, 10:00:58 PM] [Fibaro-HC2] Getting value from device:  181  parameter: Current Temperature
(node:31715) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:7:13
    at FibaroAccessory.getCharacteristicValue (/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:401:7)
    at StatusLowBattery.<anonymous> (/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:378:16)
    at StatusLowBattery.emit (events.js:387:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
    at StatusLowBattery.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1590:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
(node:31715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

**Pull request closed without merging**
