### PR TITLE
Test lint compile [DO NOT MERGE!!]

### PR DESCRIPTION
**Pull request by mkz212**

### CODE REVIEW

**Comment by mkz212** [comment]
@ilcato 
As you can see... 

IMG_4789
IMG_4790

**Comment by mkz212** [comment]
Hmm... Only it also detects old errors such as trailing spaces, etc.

**Comment by mkz212** [comment]
@ilcato 

Now i removed wrong code that i added in this PR. And now you have only one error: 

> Error:    80:9   error    'thermostatMaxTemp' is never reassigned. Use 'const' instead  prefer-const

And a few warnings.

**Comment by mkz212** [comment]
@ilcato If you want I can do PR to solve the error and most of the warnings...

**Comment by ilcato** [comment]
> @ilcato If you want I can do PR to solve the error and most of the warnings...

ok, thanks

**Comment by mkz212** [comment]
@ilcato I corrected these old errors and warnings. I gave it in one PR along with login fixes. #187

**Pull request closed without merging**
