### PR TITLE
Support for thermostats etc.

### PR DESCRIPTION
**Pull request by mkz212**
- merge climate and heating zone in one
- support for #404 (not sure if it's enough to add it and that's all?)

### CODE REVIEW

**Comment by ilcato** [comment]
> * support for [Add thermostat compatibility #404](https://github.com/ilcato/homebridge-fibaro-home-center/issues/404) (not sure if it's enough to add it and that's all?)

It's not enough, it must be managed as in HC2 but it was not stable. This is the reason I switched to Climate zones.

**Review by ilcato — COMMENTED** [review]
It's not enough, it must be managed as in HC2 but it was not stable. This is the reason I switched to Clima

**Comment by mkz212** [comment]
I don't understand. Can you fix it so it will be good?

**Comment by ilcato** [comment]
> I don't understand. Can you fix it so it will be good?

No, I was not able to stabilize it. If you want I can merge this change in order to test, but I do not have the devices.

**Comment by mkz212** [comment]
Unfortunately, I don't have these devices either. Ok, then let's wait if the user who reported that he wants support for these devices show interest in cooperation in this area.

**Comment by mkz212** [comment]
I'm closing it for now, if necessary it will open.

**Pull request closed without merging**
