### PR TITLE
A small change to better add new devices and improve existing

### PR DESCRIPTION
**Pull request by mkz212**
- Added comments to make it easier to find the right device
- Small reorder like - Moved Lightbulb to be next to Light, moved Light sensor and Multilevel sensor (temp, humidity etc.) to be next to Temperature, Humidity etc. In this way, from the top are now: Lights, Switches and Outlets, Blinds and Garage Doors, Climate (Temperature, Humidity, Brightness), Security (Motion sensor, Lock, etc.).

No code changes. Just add comments and a small swap of places.

### CODE REVIEW

**Comment by mkz212** [comment]
@ilcato still no automatic test when adding new PR

**Comment by mkz212** [comment]
@ilcato 

Yesterday someone asked for support for remote. I saw that someone had asked for it before. But I myself don't really understand why it would serve? The remote control starts some devices and I think these devices should be supported and not the remote control itself. Because it is HomeKit that acts as a pilot here. What do you think about it?

**Comment by mkz212** [comment]
@ilcato I think these two PRs and that will be all.

**Comment by ilcato** [comment]
> @ilcato still no automatic tests when adding new PR

There are no automatic tests for this project.

**Review by ilcato — APPROVED** [review]

**Pull request merged**
