### PR TITLE
fix to log error?

### PR DESCRIPTION
**Pull request by mkz212**
@ilcato Sorry ignore this PR!

### CODE REVIEW

**Comment by mkz212** [comment]
@ilcato 

A few more things:
- Poller period - what is it actually? In the sense: what is the recommended value? what if it is off and what if it is turned on? etc. I would like to add more info about it.
- Can you enable pre-checking for new PR? I'm not sure but it's probably in the Repository / Settings / Code security and analisys?
- Can you tell me how it works from the admin side? I guess the PR merge takes place in the browser? But for example, releasing a beta or stable version - how do you do that?

**Comment by ilcato** [comment]
> @ilcato Should it be "null" here? I don't suggest removing it, just shouldn't it be replaced with something?

The prototype for the get functions is: (characteristic, service, IDs, properties).
In the statement you mention the IDs param is not available so it cannot be communicated to the get functions.
The best way to improve the code is within the different get functions to check the IDs parameters before accessing it.

**Comment by mkz212** [comment]
@ilcato Can you do it? It goes beyond my knowledge and skills. Or give an example?

**Comment by ilcato** [comment]
> * Poller period - what is it actually? In the sense: what is the recommended value? what if it is off and what if it is turned on? etc. I would like to add more info about it.

it's the period between a poll and the other. I have it to 2 seconds, 1 second allows for a more responsive update of the Home app when changes appear outside the HomeKit environment. If it is disabled the Home app is not updated automatically when such a change happen but only when you close a panel and reopen it.

**Comment by ilcato** [comment]
> * Can you enable pre-checking for new PR? I'm not sure but it's probably in the Repository / Settings / Code security and analisys?

It should already be present.

**Comment by ilcato** [comment]
> * Can you tell me how it works from the admin side? I guess the PR merge takes place in the browser? But for example, releasing a beta or stable version - how do you do that? Do you just use this and this is all you need to do?:

I use npm command line interface to version and publish the package.
`npm version <version>` set the package version, it updates package.json and create a commit for it
`npm publish` push the new version into the repository and allows users to install it with `npm install ` command
I then create a release and release notes in github with the web UI
For beta versions it's only a matter of naming see [this](https://gist.github.com/adcreare/00a10f389841dd4c97197608c9b33a7f).

**Comment by ilcato** [comment]
> @ilcato Can you do it? It goes beyond my knowledge and skills. Or give an example?

Yes, when I find some time.

**Comment by mkz212** [comment]
> > * Can you tell me how it works from the admin side? I guess the PR merge takes place in the browser? But for example, releasing a beta or stable version - how do you do that? Do you just use this and this is all you need to do?:
> 
> I use npm command line interface to version and publish the package. `npm version <version>` set the package version, it updates package.json and create a commit for it `npm publish` push the new version into the repository and allows users to install it with `npm install ` command I then create a release and release notes in github with the web UI For beta versions it's only a matter of naming see [this](https://gist.github.com/adcreare/00a10f389841dd4c97197608c9b33a7f).

If I understand correctly, are there 3 stages?
1. In github you merge to main.

2. You login to npm in the browser? And there is a terminal where you enter the appropriate command? And it creates the right file / release? What exactly does such a command look? Can anyone create or just an administrator of github repository? This alone does not yet add information about the update?

3. In github you make a new release by choosing a previously created npm file? And only after that you can see it in the plugin options in Homebridge (as update or install another version)?

**Comment by ilcato** [comment]
> 1. In github you merge to main.

yes, by approving a PR

**Comment by ilcato** [comment]
> 2\. You login to npm in the browser? And there is a terminal where you enter the appropriate command? And it creates the right file / release? What exactly does such a command look? Can anyone create or just an administrator of github repository? This alone does not yet add information about the update?

No, I use the NPM command line interface through a shell (command prompt in Windows) on my machine. As I said the main 2 commands are:

1. `npm version`
2. `npm publish`

Only the admin of the package can do it.
Try to create a new package, a very simple one such as an Hello World app in nodejs, and publish it on npm. You can follow this [tutorial](https://www.freecodecamp.org/news/how-to-create-and-publish-your-first-npm-package/).

**Comment by ilcato** [comment]
> 3\. In github you make a new release by choosing a previously created npm file? And only after that you can see it in the plugin options in Homebridge (as update or install another version)?

yes for the first question. No for the second, the publishing phase will trigger the update availability. The release is used for the release notes during the update.

**Comment by mkz212** [comment]
@ilcato 

Thank you! This is how the official tutorial should look like! 👍

Additional questions:
1. I don't fully understand where the version is chosen? In the package.json file? If I change the version to the correct one, then in npm I do not have to run the npm version command? What happens if in package.json the version will be e.g. "1.2.3 beta.1" but I will use the `npm publish` command, not `npm publish --tag beta`?
2. So in Windows (or Mac) terminal first run `npm login`, next provide username and pass and next simply run `npm publish` or `npm publish --tag beta` ? How does it know which repository and which branch it is about? Is it so that one npm account is one repository from github?

**Comment by ilcato** [comment]
> @ilcato
> 
> Thank you! This is how the official tutorial should look like! 👍
> 
> Additional questions:
> 
> 1. I don't fully understand where the version is chosen? In the package.json file? If I change the version to the correct one, then in npm I do not have to run the npm version command? What happens if in package.json the version will be e.g. "1.2.3 beta.1" but I will use the `npm publish` command, not `npm publish --tag beta`?
> 2. So in Windows (or Mac) terminal first run `npm login`, next provide username and pass and next simply run `npm publish` or `npm publish --tag beta` ? How does it know which repository and which branch it is about? Is it so that one npm account is one repository from github?

1. Normally you set yhe version with the `npm version` command; it will change the package.json file correctly and commit the change into you local repository (you must `git push` the commit to the remote github repository). Don't know what happens in the other scenarios.
2. You must be in the project directory. in the package.json file there's all the information needed.

I suggest you to follow the tutorial and create a simple package to publish into npm repo using your identity.

**Pull request closed without merging**
