### PR TITLE
Fix HC2 scene execute api url

### PR DESCRIPTION
**Pull request by xlinur**

### CODE REVIEW

**Comment by ilcato** [comment]
@xlinur, please rebase your branch on the main. I completely refactor the implementation. Thanks.

**Comment by xlinur** [comment]
> @xlinur, please rebase your branch on the main. I completely refactor the implementation. Thanks.

ok

**Comment by ilcato** [comment]
@xlinur, I think we can remove the additional config parameter by inquiring the `/settings/info` endpoint of the HC API and setting the `isHC2` flag accordingly. What do you think? I'm not able to test it on the HC2. For the HC3 it respond with a `platform` property that contains `HC3` or `HC3L`. If the endpoint doesn't exist on HC2 or HC2L we can manage the not found error and assign `true` to `isHC2`.

**Comment by xlinur** [comment]
> @xlinur, I think we can remove the additional config parameter by inquiring the `/settings/info` endpoint of the HC API and setting the `isHC2` flag accordingly. What do you think? I'm not able to test it on the HC2. For the HC3 it respond with a `platform` property that contains `HC3` or `HC3L`. If the endpoint doesn't exist on HC2 or HC2L we can manage the not found error and assign `true` to `isHC2`.

I will try using /api/settings/info...

**Comment by xlinur** [comment]
@ilcato fixed - no setting isHC2

**Pull request merged**
