### PR TITLE
Ability to enable / disable new code.

### PR DESCRIPTION
**Pull request by mkz212**
Zrzut ekranu 2023-11-12 o 09 09 05

Where the change occurred:
- Wallplug group: if the Role is set to Light, Valve or Other Device.
- Binary group: if the Role is set to Other (only on HC2) and for the default value (i.e. how the Role is set to something other than Light, Valve, Other.

The problem is that in Fibaro in the Role field there is no such thing as Outlet (or anything similar). 

I think that how it is currently displayed is logical. The only problem is that when the type changes, there may be a problem. Maybe indeed the simplest method would be to give an option in config and if you turn it on it it uses the new code and if not the old one?

If you release a beta with this fix, I will test on two HCs: HC2 Lite and HC3 Lite.

### CODE REVIEW

**Comment by ilcato** [comment]
@mkz212, it's in homebridge-fibaro-home-center@1.5.0-beta.1

**Comment by mkz212** [comment]
Release beta first please

**Comment by mkz212** [comment]
@ilcato Ok i will test it and let you know

**Comment by mkz212** [comment]
On HC 3 Lite:

Update from 1.4.1 (new code) to 1.5.0. (by default old code) - without any problems even when Apple Hub turned on.
Enabling Advanced control (old code -> new code) - without any problems even when Apple Hub turned on.

Binary sensor Role: Other
Wall Plug Role: Other


I am testing further......

**Comment by mkz212** [comment]
@ilcato on another HC (HC 2 Lite). Update from 1.4.0 to 1.5.0 beta 2 without any problem. No doubled devices. Enabling Advanced control - also no problem. 

And how does it look at your place?

**Comment by ilcato** [comment]
> @ilcato on another HC (HC 2 Lite). Update from 1.4.0 to 1.5.0 beta 2 without any problem. No doubled devices. Enabling Advanced control - also no problem.
> 
> And how does it look at your place?

Not at home. And I do not have wall plugs

**Pull request merged**
