### PR TITLE
Info

### PR DESCRIPTION
**Pull request by mkz212**
@ilcato Please also add to the changelog of the next release information that if the device is displayed incorrectly or double, it should be removed from the cache first (Homebridge settings).

P.S.: When do you plan to release the next version?

### CODE REVIEW

**Comment by ilcato** [comment]
> @ilcato Please also add to the changelog of the next release information that if the device is displayed incorrectly or double, it should be removed from the cache first (Homebridge settings).
> 
> P.S.: When do you plan to release the next version?

@mkz212 please change the readme file directly with this info. I will manage versioning.

**Comment by mkz212** [comment]
@ilcato Not sure what to do? I added PR with a change in readme. Should I do it differently?

**Comment by ilcato** [comment]
> @ilcato Not sure what to do? I added PR with a change in readme. Should I do it differently?

I mean modify the last part of the readme to track the changes. I will modify the version number for the next release. 
I will release it after return home and testing with my devices.

**Comment by mkz212** [comment]
@ilcato Maybe you should merge this and release an update so that the warning be already visible? And then we will think about how to solve the problem with double display?

**Comment by mkz212** [comment]
@ilcato Undoing the introduced change is rather the worst way out because those who have already updated and have no problem will be disappointed with the loss of functionality. And it can cause them a problem even if they didn't have it before.

P.S. I'm really sorry. I remembered Apple's problem with dual devices a moment after you released the update and immediately informed about it.

**Comment by ilcato** [comment]
@mkz212, I'm not able to compile

**Comment by mkz212** [comment]
@ilcato But why?

**Comment by ilcato** [comment]
@mkz212, not a problem of typescript compiler.
When I try to npm publish it says:
 33 problems (0 errors, 33 warnings)
  0 errors and 8 warnings potentially fixable with the `--fix` option.

ESLint found too many warnings (maximum: 30).

**Comment by mkz212** [comment]
@ilcato I've never published any plugin, only PR so I don't know too much about this. But usually when there were warning, not errors it was through some space at the end of the line or something similiar. But I check this now and I cannot find anything like that.

**Comment by mkz212** [comment]
@ilcato oh.. ok.. i know!

**Comment by mkz212** [comment]
@ilcato Do you know which PR is affected by the problem? Maybe include only a part and see if it helps?

**Comment by mkz212** [comment]
@ilcato Mayby this: https://github.com/ilcato/homebridge-fibaro-home-center/pull/160 ? I wrote that I am not sure about it. Especially as to` || 0`

**Comment by mkz212** [comment]
@ilcato I completely do not understand the last message Damianod.. Nothing has changed regarding lights and icons.. Right? But recently there was a big update of the HC 3 and HC 3 Lite (to v. 5.150.15) so maybe it changed something?

**Comment by mkz212** [comment]
@ilcato Once again, I am very sorry for this situation. I think that in order to avoid similar situations in the future, it would be good to release beta versions first. Also it will be good to enable automatic PR checking.

**Comment by ilcato** [comment]
> @ilcato Once again, I am very sorry for this situation. I think that in order to avoid similar situations in the future, it would be good to release beta versions first. Also it will be good to enable automatic PR checking.

See my last post in the issue

**Comment by ilcato** [comment]
> @ilcato Mayby this: #160 ? I wrote that I am not sure about it. Especially as to` || 0`

published 1.4.1

**Comment by mkz212** [comment]
@ilcato I'm sorry to hear that you're ending up with this plugin. My adventure with Homebridge began only by the fact that the Fibaro application is hopeless and your plugin is the best that could happen to Fibaro.

As for this unfortunate mistake with dual devices, I completely forgot that Apple has such an problem. As I have already written, this is not the fault of this plugin, it applies to other plug-ins as well as other systems like Home Assistant.

I hope that apart from this one fact, I will somehow help someone with the additions / corrections introduced.

**Comment by mkz212** [comment]
@ilcato I don't know what to do now? That pinned post will probably not be useful anymore because everyone who enters there will see a long discussion that will not help him in any way.

**Pull request merged**
